[supervisord]
nodaemon=true
logfile=/dev/stdout
loglevel=info

[program:laravel]
command=php artisan serve --host=0.0.0.0 --port=%(ENV_PORT)s
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
environment=ENV_PORT="8000"

[program:queue-worker]
command=php artisan queue:work --tries=3 --timeout=90
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:reverb]
command=php artisan reverb:start
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr